mjenta-web-application-2/TennisManager.Web/Models/BookingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Microsoft.AspNet.Identity;
using Users;
using Members;
using Bookings;
using Events;
using Clubs;
using Orders;
using Kendo.Mvc.UI;
using TennisManager.Models;
using Newtonsoft.Json;


namespace TennisManager.Models
{

    public class BookingViewModel : ISchedulerEvent
    {
        [JsonProperty("Id")]
        public int Id { get; set; }

        [JsonProperty("Title")]
        public string Title { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        public int BookingCategoryId { get; set; }

        public BookingCategory BookingCategory { get; set; }

        [Display(Name = "Booking Type")]
        public int BookingTypeId { get; set; }

        public int BookingStatusId { get; set; }

        public int BookingGroupId { get; set; }

        public Member Member { get; set; }

        public Users.User User { get; set; }

        public bool? isMultiCourt { get; set; }

        public int MultiCourt { get; set; }

        public List<User> UserList { get; set; }

        public List<Customer> CustomerList { get; set; }

        public List<CustomerDisplayiewModel> CustomerCollection { get; set; }

        public List<EventDisplayViewModel> EventCollection { get; set; }

        private DateTime start;

        [Required]
        public DateTime Start
        {
            get
            {
                return start;
            }
            set
            {
                start = value.ToUniversalTime();
            }
        }


        public string StartTimezone { get; set; }

        private DateTime end;

        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DateGreaterThan(OtherField = "Start")]
        public DateTime End
        {
            get
            {
                return end;
            }
            set
            {
                end = value.ToUniversalTime();
            }
        }

        public string EndTimezone { get; set; }

        public string RecurrenceRule { get; set; }

        public int Recurrence { get; set; }

        [Display(Name = "Recurrence Option")]
        public int RecurrenceOption { get; set; }

        public string RecurrenceException { get; set; }

        public int Occurrences { get; set; }

        public bool IsAllDay { get; set; }

        public string Timezone { get; set; }
        [Required]
        public int UserId { get; set; }
        [Required]
        public int NumberOfPlayers { get; set; }

        [Display(Name = "Coach")]
        public int CoachId { get; set; }

        public Coach Coach { get; set; }

        public bool isActive { get; set; }

        public bool isPaid { get; set; }

        public decimal Price { get; set; }

        public BookingType BookingType { get; set; }

        public int Club { get; set; }
        public int FacilityId { get; set; }

        public Facility Facility { get; set; }

        public int Duration { get; set; }

        public IEnumerable<Booking> Bookings { get; set; }

        public string strBookingIds { get; set; }

        public int[] CourtIdList { get; set; }

        public List<int> recentBookingIds { get; set; }

        public IEnumerable<Order> Orders { get; set; }

        public List<OrderViewModel> OrderList { get; set; }

        public int CourtId { get; set; }

        public int[] SelectedCourts { get; set; }

        public Court Court { get; set; }

        public string strDate { get; set; }

        public string strStart { get; set; }

        public string strEnd { get; set; }

        public long longStart { get; set; }

        public long longEnd { get; set; }

        public string Search { get; set; }

        public Customer Customer { get; set; }

        public int CustomerId { get; set; }

        public double Offset { get; set; }

        [Required]
        public IEnumerable<int> CourtIds { get; set; }

        public List<Court> Courts { get; set; }

        public EventViewModel Event { get; set; }

        public EventBooking EventBooking { get; set; }

        public int EventBookingId { get; set; }

        public int EventId { get; set; }

        public string strCourts { get; set; }

        public BreadCrumbViewModel BreadCrumb { get; set; }

        public Booking ToEntity()
        {
            var booking = new Booking
            {
                
                Title = Title,
                Start = Start,
                StartTimezone = StartTimezone,
                End = End,
                EndTimezone = EndTimezone,
                Description = Description,
                IsAllDay = IsAllDay,
                RecurrenceRule = RecurrenceRule,
                RecurrenceException = RecurrenceException,
                Recurrence = Recurrence,
                UserId = UserId,
                FacilityId = FacilityId,
                BookingTypeId = BookingTypeId, 
                ClubId = Club, 
                Price = Price, 
                isActive = isActive,
                isPaid = isPaid, 
                NumberOfPlayers = NumberOfPlayers,
                CourtId = CourtId
                
            };

            return booking;
        }
    }






}

mjenta-web-application-2/TennisManager.Web/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net; 
using Kendo.Mvc.UI;
using Kendo.Mvc.Resources;
using Kendo.Mvc.Extensions;
using Microsoft.AspNet.Identity;
using Bookings;
using Orders;
using Users;
using Clubs;
using Rates;
using Events;
using Members;
using Communications;
using TennisManager.Models;
using Classification;
using TennisManager.Services;


namespace TennisManager.Controllers
{
    public class BookingController : Controller
    {

        private BookingService bookingService;
        private ClassService classService;
        private ContactService contactService;
        private CustomerService customerService;
        private SaleService saleService;

        public BookingController()
        {
            this.bookingService = new BookingService();
            this.classService = new ClassService();
            this.contactService = new ContactService();
            this.saleService = new SaleService();
            this.customerService = new CustomerService(_userManager, _signInManager);
        }

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        [Authorize]
        public ActionResult Index()
        {

            //Get User Identity
            string userId = User.Identity.GetUserId();
            int id = System.Convert.ToInt32(userId);
            Users.User user = Users.User.LoadOneById(id);

            RoleCollection roles = user.Roles;

            //Get Admin and Club Identity
            ClubAdmin admin = ClubAdmin.LoadOneByUser(id);
            Club club = Club.LoadOneById(admin.ClubId);

            List<Court> courtList = CourtCollection.LoadByClub(club).ToList();
            List<BookingType> bookingTypeList = BookingTypeCollection.LoadAll().ToList();

            ViewBag.User = user;
            ViewBag.Club = club;
            ViewBag.Courts = courtList;


            return View();
        }
       


        [Authorize]
        public virtual ActionResult RenderPartial_BookingType()
        {
                 
            return PartialView("_BookingType");
        }

        public virtual ActionResult RenderPartial_Booking_1()
        {
            return PartialView("_Booking_1");
        }

        public virtual ActionResult RenderPartial_Booking_2(BookingViewModel model)
        {
            Customer customer = Customer.LoadById(model.CustomerId);

            model.Customer = customer;

            DateTime startTime = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddMilliseconds(model.longStart);
            DateTime endTime = startTime.AddHours(1);

            model.Price = bookingService.CalculateBookingFee(model.CustomerId, model.CourtId, startTime, endTime);

            return PartialView("_Booking_2", model);
        }

        public virtual ActionResult RenderPartial_Booking_3(BookingViewModel model)
        {
            //str booking ids passed in model

            //model = bookingService.GetUnpaidBookings(model);

            //model.OrderList = bookingService.GetOutstandingBalances(model.CustomerId, 0, 0, model.strBookingIds);

            return PartialView("_Booking_3");
        }

        public virtual ActionResult RenderPartial_CustomerList(string search)
        {
            BookingViewModel model = new BookingViewModel();

            model.CustomerCollection = bookingService.GetCustomerList(search);

            return PartialView("_CustomerList", model);
        }

        public virtual ActionResult RenderPartial_ClassList(string search)
        {
            BookingViewModel model = new BookingViewModel();

            model.EventCollection = bookingService.GetClassList(search);

            return PartialView("_ClassList", model);
        }

        //public virtual ActionResult RenderPartial_ViewOutstandingBalance(int customerId, int bookingId)
        //{
        //    BookingViewModel model = new BookingViewModel()
        //    {
        //        OrderList = bookingService.GetOutstandingBalances(customerId, bookingId, 0, null)
        //    };

        //    return PartialView("_ViewOutstandingBalance", model);
        //}

        public virtual ActionResult RenderPartial_CancelBookng(int bookingId)
        {
            return PartialView("_CancelBooking");
        }

        public virtual ActionResult RenderPartial_ViewBooking(int bookingId)
        {
            BookingViewModel model = bookingService.GetBookingDetails(bookingId);

            return PartialView("_ViewBooking", model);
        }
        
        public virtual ActionResult RenderPartial_DeleteCasualBooking(BookingViewModel model)
        {
            Booking booking = Booking.Load(model.Id);
            model.User = booking.User;
            model.BookingType = booking.BookingType;
            model.Start = DateTime.SpecifyKind(booking.Start, DateTimeKind.Utc);
            model.End = DateTime.SpecifyKind(booking.End, DateTimeKind.Utc);
            model.NumberOfPlayers = booking.NumberOfPlayers;
            model.Price = booking.Price;
            model.isMultiCourt = booking.isMultiCourt;

            return PartialView("_DeleteCasualBooking", model);
        }

        public virtual ActionResult RenderPartial_Class_1(BookingViewModel model)
        {
            return PartialView("_Class_1", model);
        }

        public virtual ActionResult RenderPartial_Class_2(BookingViewModel model)
        {
            model.Event = classService.GetClassDetails(model.EventId);

            return PartialView("_Class_2", model);
        }

        public virtual ActionResult RenderPartial_ViewClass(int bookingId, int eventId)
        {
            BookingViewModel model = bookingService.GetClassBookingDetails(bookingId, eventId);

            return PartialView("_ViewClass", model);
        }

        public virtual ActionResult RenderPartial_ClassBookings(int eventBookingId)
        {
            EventViewModel model = new EventViewModel()
            {
                EventBookings = classService.GetClassBookings(eventBookingId)
            };
                     
            return PartialView("_ClassBookings", model);
        }

        public virtual ActionResult RenderPartial_Alert_AddCourt(int eventBookingId)
        {
            BookingViewModel model = new BookingViewModel()
            {
                EventBooking = EventBooking.LoadById(eventBookingId)
            };

            return PartialView("_Alert_AddCourt", model);
        }

        public virtual ActionResult RenderPartial_AddCourt(BookingViewModel model)
        {

            model.EventBooking = EventBooking.LoadById(model.EventBookingId);
            model.SelectedCourts = new int[] { model.CourtId };


            return PartialView("_AddCourt", model);
        }

        public virtual ActionResult RenderPartial_BreadCrumb(BreadCrumbViewModel model)
        {

            return PartialView("_BreadCrumb", model);
        }

        public virtual ActionResult RenderPartial_ClassDetails(BookingViewModel model)
        {

            return PartialView("_ClassDetails", model);
        }


        public virtual ActionResult RenderPartial_ClassWaitList(int eventBookingId)
        {

            EventViewModel model = classService.GetClassWaitlists(eventBookingId);

            return PartialView("_ClassWaitlist", model);
        }

        public PartialViewResult RenderPartial_ClassAttendees(int eventBookingId)
        {
            EventViewModel model = classService.GetClassRegistrations(eventBookingId);

            return PartialView("_ClassAttendees", model);
        }

        public PartialViewResult RenderPartial_ClassRegistration(EventViewModel model)
        {

            return PartialView("_ClassRegistration", model);
        }

        public PartialViewResult RenderPartial_RegisterCustomer(int eventBookingId)
        {
            EventBooking eventBooking = EventBooking.LoadById(eventBookingId);

            EventViewModel model = new EventViewModel()
            {
                EventBooking = eventBooking
            };

            return PartialView("_RegisterCustomer", model);
        }

        public PartialViewResult RenderPartial_WaitlistCustomer(int eventBookingId)
        {
            EventBooking eventBooking = EventBooking.LoadById(eventBookingId);

            EventViewModel model = new EventViewModel()
            {
                EventBooking = eventBooking
            };

            return PartialView("_WaitlistCustomer", model);
        }

        public PartialViewResult RenderPartial_SmsCustomer(int eventBookingId, bool isRegistrations)
        {
            SmsViewModel model = classService.GetSmsRecipients(eventBookingId, isRegistrations);

            return PartialView("_SmsCustomer", model);
        }

        public PartialViewResult RenderPartial_EditClassDetails(int eventBookingId)
        {
            EventViewModel model = classService.GetEventBookingDetails(eventBookingId);

            return PartialView("_ClassDetails_Edit", model);
        }

        public PartialViewResult RenderPartial_ClassBooking_Delete(int eventBookingId)
        {

            var result = classService.GetCancellationDetails(eventBookingId);

            return PartialView("_ClassBooking_Delete", result);
        }

        public PartialViewResult RenderPartial_CustomerProfile(int customerId, bool isRegistration, int eventBookingId)
        {
            EventViewModel model = new EventViewModel()
            {
                Customer = customerService.GetCustomerDetail(customerId),
                IsRegistration = isRegistration,
                EventBooking = EventBooking.LoadById(eventBookingId)
                
            };

            return PartialView("_CustomerProfile", model);
        }

mjenta-web-application-2/TennisManager.Web/Views/Booking/_Alert_AddCourt.cshtml
@model TennisManager.Models.BookingViewModel

    <div id="add-court-alert" class="alert alert-info alert-dismissable animated fadeIn">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button" onclick="addcourt_cancel()">×</button>
        <span id="add-court-description" style="font-weight:700;">
            <i class="fa fa-plus"></i>&nbsp;&nbsp;&nbsp;Add a court for @Model.EventBooking.Event.Title on @Model.EventBooking.Date.ToString("D")
        </span>
    </div>

mjenta-web-application-2/TennisManager.Web/Views/Booking/_BookingType.cshtml
@model TennisManager.Models.BookingViewModel

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <button class="btn btn-primary btn-fullwidth dim  btn-fullsize" style="margin-top:30px;" type="button" onclick="btnBookingType_click('Booking');"><i class="fa fa-calendar"></i>&nbsp;&nbsp;&nbsp;Bookings</button>
            </div>
        </div>


        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <button class="btn btn-warning btn-fullwidth dim  btn-fullsize" style="margin-top:30px;" type="button" onclick="btnClass_click();"><i class="fa fa-users"></i>&nbsp;&nbsp;&nbsp;Classes / Camps</button>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <button class="btn btn-info btn-fullwidth dim  btn-fullsize" style="margin-top:30px;" type="button"><i class="fa fa-trophy"></i>&nbsp;&nbsp;&nbsp;Competitions</button>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <button class="btn btn-default btn-fullwidth dim  btn-fullsize" style="margin-top:30px;" type="button"><i class="fa fa-paint-brush"></i>&nbsp;&nbsp;&nbsp;Maintenance</button>
            </div>
        </div>

mjenta-web-application-2/TennisManager.Web/Views/Booking/_CancelBooking.cshtml
<div class="ibox">
    <div class="ibox-title">
        <h5>Cancel Booking</h5>
        <div class="ibox-tools">
            <i class="fa fa-calendar"></i>
        </div>
    </div>
    <div class="ibox-content" style="min-height:55vh;">

        <div class="row">
            <div class="col-md-10 col-lg-offset-1">
                <h1>Are you aure you want to cancel this booking?</h1><br />
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-lg-offset-1">
                <h2>note: by cancelling a booking, the customer will be credited for the amount that has been paid.</h2>
            </div>
        </div>
    </div>

</div>


<div class="ibox" style="margin-bottom:0;">
    <div class="ibox-footer">
        <div class="row">
            <div class="col-md-12">
                <button type="button" class="btn btn-warning pull-left" onclick="CancelBooking_back()">Back</button>
                <button type="button" class="btn btn-danger pull-right" data-dismiss="modal">Cancel Booking</button>
            </div>
        </div>
    </div>
</div>

mjenta-web-application-2/TennisManager.Web/Views/Booking/_ClassAttendees.cshtml
@model TennisManager.Models.EventViewModel

@Html.HiddenFor(m => m.EventBooking.Id, new { id = "hiddenEventBookingId" })

<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>@Model.EventBooking.Date.ToString("D")</h5>
   <div class="ibox-tools">
       @Ajax.ActionLink("Edit Details", "RenderPartial_EditClassDetails", new { eventBookingId = Model.EventBooking.Id }, new AjaxOptions
          {
              HttpMethod = "GET",
              InsertionMode = InsertionMode.Replace,
              UpdateTargetId = "class-registration-container"
          }, new { @class = "btn btn-xs btn-info", style = "color:white;" })

       @Ajax.ActionLink("Cancel Booking", "RenderPartial_ClassBooking_Delete", new { eventBookingId = Model.EventBooking.Id }, new AjaxOptions
         {
             HttpMethod = "GET",
             InsertionMode = InsertionMode.Replace,
             UpdateTargetId = "class-registration-container"
         }, new { @class = "btn btn-xs btn-danger", style = "color:white;" })

   </div>
    </div>
    <div class="ibox-content" style="height:65vh; overflow:auto;">

        <div class="tabs-container">
            <ul class="nav nav-tabs">
                <li class="tab1 active"><a data-toggle="tab" href="#ClassRegistrations">Registrations</a></li>
                <li class="tab2"><a data-toggle="tab" href="#ClassWaitlist">Waitlist</a></li>
                <li class="tab3"><a data-toggle="tab" href="#ClassRoll">Roll</a></li>

            </ul>
            <div class="tab-content">
                <div id="ClassRegistrations" class="tab-pane active">
                    <div class="panel-body" style="min-height:55vh;">
                        <div id="ClassRegistrationContainer">
                            @Html.Action("RenderPartial_ClassRegistration", "Booking", Model)
                        </div>
                    </div>
                </div>
                <div id="ClassWaitlist" class="tab-pane">
                    <div class="panel-body" style="min-height:55vh;">
                        <div id="ClassWaitlistContainer">

                        </div>
                    </div>
                </div>

                <div id="ClassRoll" class="tab-pane">
                    <div class="panel-body" style="min-height:55vh;">
                        <div id="ClassRollContainer">

                        </div>
                    </div>
                </div>
            </div>

        </div>



    </div>

</div>

mjenta-web-application-2/TennisManager.Web/Views/Booking/_ClassDetails_Edit.cshtml
@model TennisManager.Models.EventViewModel

@using (Ajax.BeginForm("SaveClassDetails", "Booking", new AjaxOptions
{
    HttpMethod = "POST",
    UpdateTargetId = "class-registration-container",
    InsertionMode = InsertionMode.Replace,
    OnSuccess = "classDetailsEdit_success"
}, new { id = "SaveProductInfoForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.HiddenFor(m => m.EventBooking.Id, new { id = "hiddenEventBookingId" })

        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Edit Details for @Model.EventBooking.Date.ToString("D")</h5>
                <div class="ibox-tools">
                    @Ajax.ActionLink("Back to Registrations", "RenderPartial_ClassAttendees", new { eventBookingId = Model.EventBooking.Id }, new AjaxOptions
               {
                   HttpMethod = "GET",
                   InsertionMode = InsertionMode.Replace,
                   UpdateTargetId = "class-registration-container"
               }, new { @class = "btn btn-xs btn-primary" })
                </div>
            </div>
            <div class="ibox-content" style="height:58vh; overflow:auto;">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        @if (ViewBag.Result == "Success")
                        {
                            <div class="alert alert-success" style="margin-bottom:0;">
                                Changes have been sucessfully saved.
                            </div>
                        }

                        @if (ViewBag.Result == "Failed")
                        {
                            <div class="alert alert-danger" style="margin-bottom:0;">
                                Changes failed to save due to input errors<br />
                                @Html.ValidationSummary(true)
                            </div>
                        }
                        <hr />

                        <div class="form-group">
                            <div class="col-md-2">
                                <label>Title</label>
                            </div>
                            <div class="col-md-10">
                                @(Html.Kendo().TextBoxFor(m => m.EventBooking.Event.Title)
                                        .Name("EventBooking.Event.Title")
                                        .HtmlAttributes(new { style = "width:100%;" })
                                        .Enable(false)
                                )
                            </div>
                        </div>

                        <hr />

                        <div class="form-group">
                            <div class="col-md-2">
                                <label>Date</label>
                            </div>
                            <div class="col-md-10">
                                @(Html.Kendo().TextBox()
                                        .Name("txtDate")
                                        .Enable(false)
                                        .Value(Model.EventBooking.Date.ToString("D"))
                                        .HtmlAttributes(new { style = "width:100%;" })
                                )
                            </div>
                        </div>

                        <hr />

                        <div class="form-group">
                            <div class="col-md-2">
                                <label>Coach</label>
                            </div>
                            <div class="col-md-10">
                                @(Html.Kendo().MultiSelectFor(m => m.SelectedCoaches)
                                    .Name("SelectedCoaches")
                                    .DataValueField("Id")
                                    .DataTextField("Name")
                                    .Placeholder("Select coach/instructor(s)")
                                    .HtmlAttributes(new { style = "width:100%;" })
                                    .DataSource(source =>
                                    {
                                        source.Read(read =>
                                        {
                                            read.Action("Coaches_Read", "Booking");
                                        })
                                        .ServerFiltering(true);
                                    })
                                )
                            </div>
                        </div>

                        <hr />

                        <div class="form-group">
                            <div class="col-md-2">
                                <label>Level</label>
                            </div>
                            <div class="col-md-10">
                                @(Html.Kendo().MultiSelectFor(m => m.SelectedPlayerLevels)
                                    .Name("SelectedPlayerLevels")
                                    .DataValueField("Id")
                                    .DataTextField("Name")
                                    .Placeholder("Select skill level(s)")
                                    .HtmlAttributes(new { style = "width:100%;" })
                                    .DataSource(source =>
                                    {
                                        source.Read(read =>
                                        {
                                            read.Action("PlayerLevel_Read", "Booking");
                                        })
                                        .ServerFiltering(true);
                                    })
                                )
                            </div>
                        </div>

                        <hr />
                     
                            <div class="form-group">
                                <div class="col-md-2">
                                    <label>Court(s):</label>
                                </div>
                                <div class="col-md-10">
                                    @(Html.Kendo().MultiSelectFor(m => m.SelectedCourts)
                                            .Name("SelectedCourts")
                                            .DataValueField("Id")
                                            .DataTextField("Name")
                                            .HighlightFirst(true)
                                            .TagTemplateId("CourtTagTemplate")
                                            .ItemTemplateId("CourtItemTemplate")
                                            .Placeholder("Select court(s)...")
                                            .DataSource(source =>
                                            {
                                                source.Read(read =>
                                                {
                                                    read.Action("Courts_Read", "Booking");
                                                })
                                                .ServerFiltering(true);
                                            })
                                            .Events(e => e.Change("classcourts_changed").Open("classcourts_open"))
                                    )
                                    <small>** Remove a court by clicking on the <i class="fa fa-close"></i> symbol next to the court name </small>
                                    <br /><br />
                                    <button type="button" class="btn btn-sm btn-warning full-width" onclick="addcourt_clicked('@Model.EventBooking.Id', '@Model.EventBooking.Date.ToString("yyyy/MM/dd")')">
                                        <i class="fa fa-plus"></i>&nbsp;&nbsp;&nbsp;Add Court
                                    </button>
                                </div>
                            </div>

                    </div>
                </div>

            </div>


            <div class="ibox-footer">
                <div class="row">
                    <div class="col-md-12">
                        <button type="submit" id="btn-save-details" class="btn btn-primary pull-right">Save</button>
                    </div>
                </div>
            </div>



        </div>
    </div>
}

mjenta-web-application-2/TennisManager.Web/Views/Booking/_Class_3.cshtml
@model TennisManager.Models.BookingViewModel

@using (Ajax.BeginForm("ProcessClassPrice", "Booking", new AjaxOptions
{
    HttpMethod = "POST",
    UpdateTargetId = "BookingContainer",
    InsertionMode = InsertionMode.Replace,
    OnSuccess = "ProcessClassPriceForm_success"
}, new { id = "ProcessClassPriceForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        <div class="row">
            <div class="col-md-4 col-xs-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title text-center" style="background-color:lightblue;">
                        <i class="fa fa-book fa-2x" style="color:gray;"></i>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-xs-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title text-center" style="background-color:lightblue;">
                        <i class="fa fa-calendar fa-2x" style="color:gray;"></i>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-xs-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title text-center blue-bg">
                        <i class="fa fa-money fa-2x"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="ibox" style="margin-bottom:0;">
            <div class="ibox-title">
                <h5>3. Class Fees</h5>
                <div class="ibox-tools">
                    <i class="fa fa-money"></i>
                </div>
            </div>
            <div class="ibox-content" style="min-height:45vh;">

                <label>form goes here...</label>






            </div>
            <div class="ibox-footer">
                <button type="button" class="btn btn-warning">Back</button>
                <button type="submit" class="btn btn-primary pull-right">Next</button>
            </div>
        </div>
    </div>
}